version: '3.5'

services:

  abpi:
    container_name: abpi
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    links:
      - mongo

  mongo:
    image: "mongo:3.4"
    container_name: "mongodb"
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017